import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { decode, encode, canonicalize, canonicalHash, decimal, hexBytes, EncodingError, EncodingLimit } from '../../tools/tc0/canonical.mjs';
const bytes = s => Buffer.from(s, 'utf8');

// Hand-derived transport vectors from TC0/0.2 §2, not generated by the implementation.
const vectors = [
  [' { "z":true, "A":"1", "_":null, "a":false } ', '{"A":"1","_":null,"a":false,"z":true}'],
  ['["\\n","\\t","\\r","\\b","\\f","\\u001F"]', '["\\u000a","\\u0009","\\u000d","\\u0008","\\u000c","\\u001f"]'],
  ['["\\/","\\u00e9","\\ud83d\\ude00"]', '["/","é","😀"]'],
  ['["\\\"","\\\\", "e\\u0301"]', '["\\\"","\\\\","é"]'],
  ['{"__proto__":"safe","constructor":[]}', '{"__proto__":"safe","constructor":[]}'],
];
for (const [input, expected] of vectors) test(`canonical bytes ${input}`, () => {
  assert.equal(canonicalize(bytes(input)).toString('hex'), bytes(expected).toString('hex'));
  assert.equal(canonicalize(bytes(expected)).toString(), expected);
  assert.equal(canonicalHash(bytes(input)), createHash('sha256').update(bytes(expected)).digest('hex'));
});

test('published hand vectors remain executable', () => {
  const corpus = JSON.parse(readFileSync(new URL('../../spec/tc0/transport-vectors.json', import.meta.url)));
  for (const row of corpus.accept) {
    assert.equal(canonicalize(bytes(row.input)).toString('hex'), bytes(row.canonical).toString('hex'), row.id);
  }
  for (const row of corpus.reject) {
    const input = row.input_hex ? Buffer.from(row.input_hex, 'hex') : bytes(row.input);
    assert.throws(() => decode(input), EncodingError, row.id);
  }
});

test('all control characters use lowercase long escapes', () => {
  const raw = Array.from({length: 32}, (_, i) => String.fromCharCode(i)).join('');
  const expected = '"' + Array.from({length: 32}, (_, i) => '\\u00' + i.toString(16).padStart(2, '0')).join('') + '"';
  assert.equal(encode(raw).toString(), expected);
});
test('no Unicode normalization', () => {
  assert.notEqual(canonicalHash(bytes('"é"')), canonicalHash(bytes('"é"')));
});
test('duplicate decoded keys rejected at every nesting level', () => {
  for (const raw of ['{"a":null,"a":true}', '{"a":null,"\\u0061":true}', '[{"x":{"y":false,"y":null}}]']) {
    assert.throws(() => decode(bytes(raw)), EncodingError);
  }
});
test('invalid JSON, numeric tokens, keys and surrogates reject', () => {
  for (const raw of ['0', '-0', '1e2', '[1]', '{"x":1}', '{"":null}', '{"é":null}',
    '{"a-b":null}', '"\\ud800"', '"\\udc00"', '"\\ud800x"',
    '"\\x01"', '"a\nb"', '[true,]', '{"x":null,}', 'null null', 'truex', '[', '{', '"',
    '\ufeffnull', '\u00a0null', 'undefined', 'NaN']) {
    assert.throws(() => decode(bytes(raw)), EncodingError, raw);
  }
  // JS's UTF-8 encoder replaces lone raw surrogates; test raw code units through encode instead.
  assert.throws(() => encode('\ud800'), EncodingError);
});
test('invalid UTF-8 fails, never replaced', () => {
  for (const data of [[0xc0,0xaf], [0xed,0xa0,0x80], [0xf4,0x90,0x80,0x80], [0x22,0xc3,0x22]]) {
    assert.throws(() => decode(Uint8Array.from(data)), EncodingError);
  }
});
test('encoder rejects nontransport values, cycles, holes, hidden data and accessors', () => {
  const cycle = []; cycle.push(cycle);
  for (const v of [1, 1n, undefined, new Date(), cycle, Array(1), {x: undefined},
    {get x() {throw new Error('must not execute');}}, {[Symbol()]: null},
    Object.defineProperty({}, 'x', {value: null})]) assert.throws(() => encode(v), EncodingError);
  const extended = []; extended.x = null;
  assert.throws(() => encode(extended), EncodingError);
  const alias = ['x']; assert.equal(encode([alias,alias]).toString(), '[["x"],["x"]]');
});
test('explicit resource caps never silently accept', () => {
  assert.throws(() => decode(bytes('null'), {maxBytes:3}), EncodingLimit);
  assert.throws(() => encode('😀', {maxBytes:5}), EncodingLimit);
  assert.throws(() => decode(bytes('[[null]]'), {maxDepth:1}), EncodingLimit);
  assert.throws(() => encode([[null]], {maxDepth:1}), EncodingLimit);
  assert.throws(() => decode(bytes('[null,null]'), {maxValues:2}), EncodingLimit);
  assert.throws(() => encode([null,null], {maxValues:2}), EncodingLimit);
  assert.equal(decode(bytes('null'), {maxBytes:4}), null);
  assert.throws(() => decode(bytes('null'), {maxDepth:0}), TypeError);
  assert.throws(() => decode(bytes('null'), {toString:1}), TypeError);
});
test('decimal and bytes field grammars are separate from transport strings', () => {
  for (const v of ['0', '1', '-1', '9223372036854775808']) assert.equal(decimal(v), v);
  for (const v of ['', '+1', '01', '-0', '-01', '1.0', ' 1', 1]) assert.throws(() => decimal(v), EncodingError);
  assert.throws(() => decimal('-1', {unsigned:true}), EncodingError);
  assert.equal(decimal('0', {unsigned:true}), '0');
  for (const v of ['', '00', 'ff012a']) assert.equal(hexBytes(v), v);
  for (const v of ['a','FF','0x00','00 ']) assert.throws(() => hexBytes(v), EncodingError);
});
