package main

import (
	"encoding/json"
	"strings"
	"testing"
)

// Hand-written adapter bytes, not generated by the implementation under test.
const unitBridgeHeader = `/* Validated artifact DATA ONLY, not precomputed transitions. */
#define NA_ARTIFACT_SHA256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#define NA_INPUT_SHA256 "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
static const struct na_node na_nodes[]={
{0,UINT64_C(2),UINT64_C(0),-1,{0,0},"",0,{-1,-1,-1}}
};
static const unsigned na_node_count=1;
static const unsigned na_root=0;
static const uint64_t na_parameter=UINT64_C(1);
static const struct na_value na_input={0,0};
`

func TestHeaderLiteralRepresentation(t *testing.T) {
	cases := []struct {
		value []any
		want  string
	}{
		{[]any{"unit"}, "{0,0}"},
		{[]any{"bool", false}, "{1,0}"},
		{[]any{"bool", true}, "{1,1}"},
		{[]any{"int", "0"}, "{2,INT64_C(0)}"},
		{[]any{"int", "-7"}, "{2,(-INT64_C(7))}"},
		{[]any{"int", "9007199254740993"}, "{2,INT64_C(9007199254740993)}"},
		{[]any{"int", "9223372036854775807"}, "{2,INT64_C(9223372036854775807)}"},
		{[]any{"int", "-9223372036854775808"}, "{2,(-INT64_C(9223372036854775807)-1)}"},
	}
	for _, c := range cases {
		got, e := headerLiteral(c.value)
		if e != nil || got != c.want {
			t.Fatalf("%v: %q, %v; want %q", c.value, got, e, c.want)
		}
	}
	bad := [][]any{nil, {}, {"unit", "extra"}, {"bool", "true"}, {"int", "+1"}, {"int", "01"}, {"int", "-0"}, {"int", "9223372036854775808"}, {"int", "1);#error"}, {"bytes", "00"}, {map[string]any{}, "x"}}
	for _, v := range bad {
		if _, e := headerLiteral(v); e == nil {
			t.Fatalf("unsafe literal admitted: %v", v)
		}
	}
}

func TestHeaderTokensRejectUnsafeRepresentation(t *testing.T) {
	changes := map[string]func(map[string]any){
		"digest injection":    func(d map[string]any) { d["artifact_sha256"] = "\"\\n#error" },
		"uppercase digest":    func(d map[string]any) { d["input_sha256"] = strings.Repeat("B", 64) },
		"parameter injection": func(d map[string]any) { d["parameter"] = "1);#error" },
		"parameter overflow":  func(d map[string]any) { d["parameter"] = "18446744073709551616" },
		"id spelling":         func(d map[string]any) { d["rows"].([]any)[0].(map[string]any)["id"] = "02" },
		"label injection":     func(d map[string]any) { d["rows"].([]any)[0].(map[string]any)["label"] = "\"\\n#error" },
		"unknown tag":         func(d map[string]any) { d["rows"].([]any)[0].(map[string]any)["tag"] = "call" },
		"unknown op":          func(d map[string]any) { d["rows"].([]any)[0].(map[string]any)["op"] = "arbitrary" },
	}
	for name, change := range changes {
		t.Run(name, func(t *testing.T) {
			var envelope loweringEnvelope
			if e := decodeHostJSON(bridgeFixture(t, change), &envelope); e != nil {
				t.Fatal(e)
			}
			if _, e := loweringDataHeader(envelope.Data); e == nil {
				t.Fatal("unsafe representation admitted")
			}
		})
	}
}

func TestNativeBridgeHeaderContradictions(t *testing.T) {
	changes := map[string][2]string{
		"artifact":    {strings.Repeat("a", 64), strings.Repeat("c", 64)},
		"input hash":  {strings.Repeat("b", 64), strings.Repeat("c", 64)},
		"count":       {"na_node_count=1", "na_node_count=2"},
		"root":        {"na_root=0", "na_root=1"},
		"parameter":   {"na_parameter=UINT64_C(1)", "na_parameter=UINT64_C(2)"},
		"input value": {"na_input={0,0}", "na_input={1,1}"},
		"row tag":     {"{0,UINT64_C(2)", "{1,UINT64_C(2)"},
		"row id":      {"UINT64_C(2)", "UINT64_C(3)"},
		"binding":     {"UINT64_C(0)", "UINT64_C(1)"},
		"operator":    {"-1,{0,0}", "0,{0,0}"},
		"literal":     {"-1,{0,0}", "-1,{2,INT64_C(7)}"},
		"label":       {`"",0,`, `"extra",0,`},
		"children":    {"0,{-1,-1,-1}", "1,{0,-1,-1}"},
		"appended C":  {"na_input={0,0};\n", "na_input={0,0};\n#error appended\n"},
	}
	for name, change := range changes {
		t.Run(name, func(t *testing.T) {
			var envelope map[string]any
			if e := json.Unmarshal(bridgeFixture(t, nil), &envelope); e != nil {
				t.Fatal(e)
			}
			header := strings.Replace(unitBridgeHeader, change[0], change[1], 1)
			if header == unitBridgeHeader {
				t.Fatal("ineffective vector")
			}
			envelope["header"] = header
			b, e := json.Marshal(envelope)
			if e != nil {
				t.Fatal(e)
			}
			if _, e = decodeNativeAdmission(b); e == nil {
				t.Fatal("contradictory header admitted")
			}
		})
	}
}

func TestNativeBridgeDataContradictions(t *testing.T) {
	changes := map[string]func(map[string]any){
		"artifact":   func(d map[string]any) { d["artifact_sha256"] = strings.Repeat("c", 64) },
		"input hash": func(d map[string]any) { d["input_sha256"] = strings.Repeat("c", 64) },
		"parameter":  func(d map[string]any) { d["parameter"] = "3" },
		"input":      func(d map[string]any) { d["input"] = []any{"bool", true} },
		"row":        func(d map[string]any) { d["rows"].([]any)[0].(map[string]any)["id"] = "3" },
	}
	for name, change := range changes {
		t.Run(name, func(t *testing.T) {
			if _, e := decodeNativeAdmission(bridgeFixture(t, change)); e == nil {
				t.Fatal("contradictory data admitted")
			}
		})
	}
}
